### PUT request to update patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe",
  "address": "Test address 12, 12039",
  "email": "john.doe@email.com",
  "dateOfBirth": "2000-01-02"
}

###
